# Generated by Django 5.2 on 2025-04-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='link',
            field=models.URLField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
